<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="0" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="suite1" duration-ms="9" started-at="2018-10-12T07:28:49Z" finished-at="2018-10-12T07:28:49Z">
    <groups>
    </groups>
    <test name="EVOKE TEST " duration-ms="9" started-at="2018-10-12T07:28:49Z" finished-at="2018-10-12T07:28:49Z">
      <class name="utility.Utility">
        <test-method status="PASS" signature="startReport()[pri:0, instance:utility.Utility@369f73a2]" name="startReport" is-config="true" duration-ms="811" started-at="2018-10-12T07:28:48Z" finished-at="2018-10-12T07:28:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method status="PASS" signature="setUpBrowser(java.lang.String)[pri:0, instance:utility.Utility@369f73a2]" name="setUpBrowser" is-config="true" duration-ms="4" started-at="2018-10-12T07:28:49Z" finished-at="2018-10-12T07:28:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBrowser -->
        <test-method status="FAIL" signature="endReport()[pri:0, instance:utility.Utility@369f73a2]" name="endReport" is-config="true" duration-ms="14601" started-at="2018-10-12T07:28:49Z" finished-at="2018-10-12T07:29:04Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[javax.mail.AuthenticationFailedException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: javax.mail.AuthenticationFailedException
at utility.Utility.execute(Utility.java:504)
at utility.Utility.endReport(Utility.java:116)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: javax.mail.AuthenticationFailedException
at javax.mail.Service.connect(Service.java:306)
at javax.mail.Service.connect(Service.java:156)
at javax.mail.Service.connect(Service.java:105)
at javax.mail.Transport.send0(Transport.java:168)
at javax.mail.Transport.send(Transport.java:98)
at utility.Utility.execute(Utility.java:498)
... 21 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- utility.Utility -->
    </test> <!-- EVOKE TEST  -->
  </suite> <!-- suite1 -->
</testng-results>
